version: "3"
services:
  server:                          
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app  
      - /usr/src/app/node_modules      
    environment:
      - PORT=3000
    networks:
      - backend  
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: lunarcat1234!
    networks:
      - backend

  nginx:
    restart: always
    image: nginx
    volumes: 
      - ./epiclogue.ssl:/ssl
      - ./epiclogue.ssl/server.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - backend
    

networks: 
  backend:
    driver: bridge